services:
  newsaggr:
    build: .
    ports:
      - '4444:4444'
    volumes:
      - newsaggr_data:/usr/app/.data
    environment:
      - GITHUB_CLIENT_ID=
      - GITHUB_CLIENT_SECRET=
      - JWT_SECRET=
      - INIT_TABLE=true
      - ENABLE_CACHE=true

volumes:
  newsaggr_data:
    name: newsaggr_data
